# Generated by Django 5.0.4 on 2025-06-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='features_image',
            new_name='featured_image',
        ),
    ]
